# Generated by Django 5.2.3 on 2025-06-15 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Student Email')),
                ('semester', models.Field(blank=True, choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='teacher Full Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='teacher Email')),
                ('department', models.Field(blank=True, choices=[('BEI', 'Bachelor of Electronics and Information'), ('BCT', 'Bachelor of Computer Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', null=True)),
                ('phone_no', models.IntegerField()),
                ('join_data', models.DateField(default='Join Data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
