# Generated by Django 5.2.3 on 2025-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_department_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCT', 'Bachelor of Computer Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=20, null=True),
        ),
    ]
