# Generated by Django 5.2.3 on 2025-06-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BCE', 'Bachelor of Civil Engineering'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information')], default='N/A', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Material Title')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of Material')),
                ('uploaded_date', models.DateField(default='Uploaded_Date', verbose_name='Uploaded_Date')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By')),
            ],
        ),
    ]
