# Generated by Django 5.2.3 on 2025-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teacher_department_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCE', 'Bachelor of Civil Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BEI', 'Bachelor of Electronics and Information'), ('BCT', 'Bachelor of Computer Engineering')], default='N/A', max_length=20, null=True),
        ),
    ]
