# Generated by Django 5.2.3 on 2025-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-title'], 'verbose_name': 'assignment', 'verbose_name_plural': 'assignments'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title'], 'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-full_name'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCE', 'Bachelor of Civil Engineering'), ('BCT', 'Bachelor of Computer Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BEI', 'Bachelor of Electronics and Information')], default='N/A', max_length=20, null=True),
        ),
    ]
