# Generated by Django 5.2.3 on 2025-06-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_assignment_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-full_name'], 'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BEI', 'Bachelor of Electronics and Information'), ('BCT', 'Bachelor of Computer Engineering'), ('BCE', 'Bachelor of Civil Engineering'), ('BCA', 'Bachelor of Computer Application')], default='N/A', max_length=20, null=True),
        ),
    ]
