# Generated by Django 5.2.3 on 2025-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teacher_options_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('System Analysis and Design', 'BCT002'), ('Data Structure', 'BCT003'), ('BCT004', 'Data Communication'), ('BCT005', 'Mathematics')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('System Analysis and Design', 'BCT002'), ('Data Structure', 'BCT003'), ('BCT004', 'Data Communication'), ('BCT005', 'Mathematics')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCA', 'Bachelor of Computer Application'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=20, null=True),
        ),
    ]
