# Generated by Django 5.2.3 on 2025-06-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignment_subject_alter_material_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Material_file',
            field=models.FileField(blank=True, default='N/A', null=True, upload_to='material', verbose_name='select file'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('A text book', 'TEXT_BOOK'), ('REFERENCE_BOOK', 'A reference boook'), ('OLD_QUESTION', 'Precious board exam question'), ('AUDIO_BOOK', 'An audio book')], default='N/A', max_length=20, verbose_name='select category'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Data Structure'), ('BCT004', 'Data Communication'), ('BCT005', 'Mathematics')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=255, null=True, verbose_name='Description of Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Data Structure'), ('BCT004', 'Data Communication'), ('BCT005', 'Mathematics')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCE', 'Bachelor of Civil Engineering'), ('BCT', 'Bachelor of Computer Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BEI', 'Bachelor of Electronics and Information')], default='N/A', max_length=20, null=True),
        ),
    ]
