# Generated by Django 5.2.3 on 2025-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_material_material_file_material_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('System Analysis and Design', 'BCT002'), ('Data Structure', 'BCT003'), ('Data Communication', 'BCT004'), ('Mathematics', 'BCT005')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Chapter Slide', 'SLIDE'), ('A text book', 'TEXT_BOOK'), ('A reference boook', 'REFERENCE_BOOK'), ('Precious board exam question', 'OLD_QUESTION'), ('AUDIO_BOOK', 'An audio book')], default='N/A', max_length=30, verbose_name='select category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('Software Engineering', 'BCTOO1'), ('System Analysis and Design', 'BCT002'), ('Data Structure', 'BCT003'), ('Data Communication', 'BCT004'), ('Mathematics', 'BCT005')], default='N/A', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering')], default='N/A', max_length=20, null=True),
        ),
    ]
